name: ASkyblock-Redefined
version: ${version}
description: Skyblock Redefined
main: com.iridium.iridiumskyblock.IridiumSkyblock
api-version: '1.13' # TODO: 1.19?
author: Peaches_MLG
depend: [ Vault ]
softdepend:
  - "MVdWPlaceholderAPI"
  - "PlaceholderAPI"
  - "Essentials"
  - "EssentialsSpawn"
  - "RoseStacker"
  - "WorldEdit"
loadbefore:
  - "Multiverse-Core"
commands:
  iridiumskyblock:
    aliases: [ "island", is ]
    description: Main plugin command
